MovieApp.UI/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Core.Domain.Entites;
using MovieApp.Core.Domain.IdentityEntites;
using MovieApp.Core.DTO;
using MovieApp.Core.Enumerator;
using MovieApp.Core.Services;
using MovieApp.Core.ServicesContracts;
using MovieApp.Infrastructure.ApplicationDbContext;

namespace MovieApp.UI.Controllers
{
    [Route("[controller]/[action]")]
    public class MovieController : Controller
    {
        private readonly IMovieServices _movieServices;
        private readonly IGenreServices _genreServices;
        private readonly IFavouriteServices _favouriteServices;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly AppDbContext _db;
        public MovieController(IMovieServices movieServices , 
            IGenreServices genreServices,
            UserManager<ApplicationUser> userManager,
            IFavouriteServices favouriteServices,
            AppDbContext db)
        {
            _movieServices = movieServices;
            _genreServices = genreServices;
            _userManager = userManager;
            _favouriteServices = favouriteServices;
            _db = db;
        }

        [HttpGet]
        [Route("/")]
        [AllowAnonymous]
        public async Task<IActionResult> Index(string? searchString, string sortBy = nameof(Movie.Rating), string sorted = "DESC")
        {
            IEnumerable<MovieResponse> movies = await _movieServices.GetAllMovies();

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = await _movieServices.GetFilteredMovies(nameof(MovieAddRequest.Title), searchString);
            }

            ViewBag.currentSearchString = searchString;
            ViewBag.currentSortBy = sortBy;
            ViewBag.currentSorted = sorted;

            ViewBag.sortByList = new List<SelectListItem>
            {
                new SelectListItem { Text = "Title", Value = nameof(Movie.Title) },
                new SelectListItem { Text = "Rating", Value = nameof(Movie.Rating) },
                new SelectListItem { Text = "Release Date", Value = nameof(Movie.ReleaseDate) }
             };

            List<MovieResponse>moviesSorted = (await _movieServices.SortedMovies(movies.ToList(), sortBy, sorted == "ASC" ? SortedOption.ASC : SortedOption.DESC)).ToList();

            return View(moviesSorted);
        }

        [HttpGet]
        [Authorize(Roles =nameof(UserOption.ADMIN))]
        public async Task<IActionResult> Create()
        {
            var genres = await _genreServices.GetAllGenre();

            ViewBag.Genres = genres.Select(x =>
                new SelectListItem() { Text = x.GenreName, Value = x.GenreID.ToString() }
            ).ToList();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(UserOption.ADMIN))]
        public async Task<IActionResult> Create(MovieAddRequest movieAddRequest)
        {
            if(!ModelState.IsValid)
            {
                var genres = await _genreServices.GetAllGenre();
                ViewBag.Genres = genres.Select(x =>
                    new SelectListItem() { Text = x.GenreName, Value = x.GenreID.ToString() }
                ).ToList();
                ViewBag.Errors = ModelState.Values
                    .SelectMany(x => x.Errors)
                    .Select(x => x.ErrorMessage);
                return View(movieAddRequest);
            }
          
            await _movieServices.AddMovie(movieAddRequest);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Details(Guid? movieID)
        {
            MovieResponse movie = await _movieServices.GetMovieByMovieID(movieID);

            return View(movie);
        }
        [HttpGet]
        [Authorize(Roles = nameof(UserOption.ADMIN))]
        public async Task<IActionResult> Edit(Guid? movieID)
        {
            var movieBefore = await _movieServices.GetMovieByMovieID(movieID);
            var genres = await _genreServices.GetAllGenre();
            if (movieBefore == null)
                return NotFound();

            ViewBag.Genres = genres.Select(x =>
                new SelectListItem() { Text = x.GenreName, Value = x.GenreID.ToString() }
            ).ToList();
            var movieUpdateRequest = new MovieUpdateRequest()
            {
                Title = movieBefore.Title,
                Description = movieBefore.Description,
                GenreID = movieBefore.GenreID,
                ImageURL = movieBefore.ImageURL,
                MovieID = movieBefore.MovieID,
                Rating = movieBefore.Rating,
                ReleaseDate = movieBefore.ReleaseDate
            };

            return View(movieUpdateRequest);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(UserOption.ADMIN))]
        public async Task<IActionResult> Edit(MovieUpdateRequest movieUpdate)
        {
            if (!ModelState.IsValid)
            {
                var genres = await _genreServices.GetAllGenre();
                ViewBag.Genres = genres.Select(x =>
                    new SelectListItem() { Text = x.GenreName, Value = x.GenreID.ToString() }
                ).ToList();
                ViewBag.Errors = ModelState.Values
                    .SelectMany(x => x.Errors)
                    .Select(x => x.ErrorMessage);
                return View(movieUpdate);
            }
            await _movieServices.UpdateMovies(movieUpdate);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = nameof(UserOption.ADMIN))]
        public async Task<IActionResult>Delete(Guid? movieID)
        {
            await _movieServices.DeleteMovieByMovieID(movieID);
            return RedirectToAction("Index");
        }

    }
}

MovieApp.UI/Controllers/MovieFavouriteController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieApp.Core.Domain.Entites;
using MovieApp.Core.Domain.IdentityEntites;
using MovieApp.Core.DTO;
using MovieApp.Core.Enumerator;
using MovieApp.Core.ServicesContracts;

public class MovieFavouriteController : Controller
{
    private readonly IMovieFavouriteServices _movieFavouriteServices;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IMovieServices _movieServices;
    private readonly IFavouriteServices _favouriteServices;

    public MovieFavouriteController(IMovieFavouriteServices movieFavouriteServices,
        UserManager<ApplicationUser> userManager,
        IMovieServices movieServices,
        IFavouriteServices favouriteServices)
    {
        _movieFavouriteServices = movieFavouriteServices ;
        _userManager = userManager ;
        _movieServices = movieServices;
        _favouriteServices = favouriteServices;
    }
    [HttpGet]
    public async Task<IActionResult> Index(string? searchString, string sortBy = nameof(Movie.Rating), string sorted = "DESC")
    {
        var user = await _userManager.GetUserAsync(User);
        if(user == null) 
            return Unauthorized();

        IEnumerable<MovieResponse> movies = await _movieFavouriteServices
            .GetFavouriteMoviesByUser(user.Id);

        if (!string.IsNullOrEmpty(searchString))
        {
            movies = await _movieServices.GetFilteredMovies(nameof(MovieAddRequest.Title), searchString);
        }

        ViewBag.currentSearchString = searchString;
        ViewBag.currentSortBy = sortBy;
        ViewBag.currentSorted = sorted;

        ViewBag.sortByList = new List<SelectListItem>
        {
             new SelectListItem { Text = "Title", Value = nameof(Movie.Title) },
             new SelectListItem { Text = "Rating", Value = nameof(Movie.Rating) },
             new SelectListItem { Text = "Release Date", Value = nameof(Movie.ReleaseDate) }
        };

        List<MovieResponse> moviesSorted = (await _movieServices.SortedMovies(movies.ToList(), sortBy, sorted == "ASC" ? SortedOption.ASC : SortedOption.DESC)).ToList();

        return View(moviesSorted);
    }

    [HttpGet]
    public async Task<IActionResult> AddMovieToUser(Guid? movieID)
    {
        var user = await _userManager.GetUserAsync(User);

        if (user == null)
            return Unauthorized();

        var movie = await _movieServices.GetMovieByMovieID(movieID);

        if (movie == null)
            return NotFound();

        bool haveFavourite = await _favouriteServices.HaveFavourite(user.Id);
        bool moviefound = await _movieFavouriteServices.IsMovieInUserFavourites(movieID, user.Id);
        if (moviefound)
        {
            TempData["Message"] = "Movie is already added to favorites.";
            return RedirectToAction("Index");
        }

        MovieFavourite movieFavourite = new MovieFavourite
        {
            MovieID = movieID.Value
        };

        if (!haveFavourite)
        {
            var favouriteAddRequest = new FavouriteAddRequest { UserID = user.Id };
            var favouriteResponse = await _favouriteServices.CreateFavourite(favouriteAddRequest);
            movieFavourite.FavouriteID = favouriteResponse.FavouriteID;
        }
        else
        {
            var favourite = await _favouriteServices.GetFavouriteByUserId(user.Id);
            movieFavourite.FavouriteID = favourite.FavouriteID;
        }

        await _movieFavouriteServices.AddMovieToFavourite(movieFavourite);
        TempData["Message"] = "Movie added to favorites successfully.";
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> RemoveMovieFromUser(Guid? movieID)
    {
        var user =await _userManager.GetUserAsync(User);
        if (user == null)
            return Unauthorized();

        var movie = await _movieServices.GetMovieByMovieID(movieID);
        var favourite = await _favouriteServices.GetFavouriteByUserId(user.Id);
        if(movie == null)
            return NotFound();

        await _movieFavouriteServices.DeleteMovieFromFavourite(movieID.Value, favourite.FavouriteID);

        return RedirectToAction("Index");
    }

}

MovieApp.UI/Views/Movie/Create.cshtml
@model MovieAddRequest
@{
    ViewBag.Title = "Create";
}
<h2 class="display-4">Create Movie</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" asp-controller="Movie" method="post" enctype="multipart/form-data">
            <div class="form-group mt-2 w-75">
                <label asp-for="Title" class="form-label font-monospace">Title:</label>
                <input asp-for="Title" class="form-control" maxlength="100" required />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mt-2 w-75">
                <label asp-for="GenreID" class="form-label font-monospace">Genre: </label>
                <select asp-for="GenreID" asp-items="ViewBag.Genres" class="form-select" required>
                    <option value="">--Select Genre--</option>
                </select>
                <span asp-validation-for="GenreID" class="text-danger"></span>
            </div>
            <div class="form-group w-50 mt-2">
                <label asp-for="ReleaseDate" class="form-label font-monospace" class="form-label">Release Date: </label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-2 w-25">
                <label asp-for="Rating" class="form-label font-monospace">Rate: </label>
                <input asp-for="Rating" class="form-control" min="1" max="10" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-floating w-75 mt-2">
                <textarea asp-for="Description" class="form-control" placeholder="Leave a StoryLine Here" id="floatingTextarea2" style="height: 100px" maxlength="1000"></textarea>
                <label asp-for="Description" for="floatingTextarea2">StoryLine</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3 mt-2 w-75">
                <label asp-for="Poster" class="form-label">Choose Image</label>
                <input asp-for="Poster" type="file" class="form-control" id="imageInput" accept=".png,.jpg" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary mt-2">
                <i class="bi bi-check"></i>
                Save
            </button>
            <a asp-action="Index" class="btn btn-outline-warning mt-2">
                <i class="bi bi-x"></i>
                Cancel
            </a>
        </form>
    </div>
    <div class="col-md-6">
        <div id="posterImg" class="d-none">
            <img src="" alt="Poster Image" class="img-thumbnail" id="posterImage">
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial"></partial>
    <script>
        $(document).ready(function () {
            $('#imageInput').on('change', function () {
                var file = this.files[0];
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#posterImg').removeClass('d-none');
                    $('#posterImage').attr('src', e.target.result);
                    $('#imageValidation').text('');
                }

                reader.readAsDataURL(file);
            });
            $('#Year').datepicker({
                format: 'yyyy',
                viewMode: 'years',
                minViewMode: 'years',
                autoclose: true,
                startDate: new Date('1950-01-01'),
                endDate: new Date()
            });
        });
    </script>
}

MovieApp.UI/Views/Movie/Details.cshtml
@model MovieResponse
@{
    ViewData["Title"] = Model.Title;
}
<div class="d-flex justify-content-between align-items-center mb-3">
    <a asp-action="Index" class="btn btn-primary">
        <i class="bi bi-skip-backward-fill"></i>
        Back
    </a>
</div>
<div class="row justify-content-between mt-5">
    <div class="col-md-3">
        <img src="/Upload/@Model.ImageURL" class="img-thumbnail" alt="@Model.Title" />
    </div>
    <div class="col-md-7">
        <div class="d-flex justify-content-between mb-3 align-items-center">
            <h3 class="mb-0">@Model.Title</h3>
            <span class="d-flex align-items-center">
                <i class="bi bi-star-fill text-warning mr-1"></i>
                <span class="text-muted">@Model.Rating?.ToString("0.0")</span>
            </span>
        </div>
        <div class="d-flex align-items-center mb-2">
            <span class="text-muted mr-5">
                <i class="bi bi-calendar-week"></i>
                @Model.ReleaseDate?.ToString("yyyy")
            </span>
            <span class="text-muted mr-5">
                <i class="bi bi-clock-history"></i>
                @Model.ProducedSince Y
            </span>
            <span class="text-muted mr-5">
                <i class="bi bi-film"></i>
                @Model.GenreName
            </span>
        </div>
        <p class="text-justify mt-3">@Model.Description</p>
    </div>
</div>

MovieApp.UI/Views/Movie/Edit.cshtml
@model MovieUpdateRequest
@{
    ViewBag.Title = "Edit";
}
<h2 class="display-4">Edit Movie</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" asp-controller="Movie" method="post" enctype="multipart/form-data" asp-route-movieID="@Model.MovieID">
            <div class="form-group mt-2 w-75">
                <label asp-for="Title" class="form-label font-monospace">Title:</label>
                <input asp-for="Title" class="form-control" maxlength="100" required />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mt-2 w-75">
                <label asp-for="GenreID" class="form-label font-monospace">Genre: </label>
                <select asp-for="GenreID" asp-items="ViewBag.Genres" class="form-select" required>
                    <option value="">--Select Genre--</option>
                </select>
                <span asp-validation-for="GenreID" class="text-danger"></span>
            </div>
            <div class="form-group w-50 mt-2">
                <label asp-for="ReleaseDate" class="form-label font-monospace" class="form-label">Release Date: </label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-2 w-25">
                <label asp-for="Rating" class="form-label font-monospace">Rate: </label>
                <input asp-for="Rating" class="form-control" min="1" max="10" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-floating w-75 mt-2">
                <textarea asp-for="Description" class="form-control" placeholder="Leave a StoryLine Here" id="floatingTextarea2" style="height: 100px" maxlength="1000"></textarea>
                <label asp-for="Description" for="floatingTextarea2">StoryLine</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mt-2 w-75 mb-3">
                <label asp-for="Poster" class="form-label font-monospace">Poster: </label>
                <input asp-for="Poster" type="file" class="form-control" id="imageInput" accept=".jpg, .png" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary mt-2">
                <i class="bi bi-check"></i>
                Save
            </button>
            <a asp-action="Index" class="btn btn-outline-warning mt-2">
                <i class="bi bi-x"></i>
                Cancel
            </a>
        </form>
    </div>
    <div class="col-md-6">
        <div id="posterImg" class="@String.Empty">
            <img src="/Upload/@Model.ImageURL" alt="" class="img-thumbnail" id="posterImage">
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial"></partial>
    <script>
        $(document).ready(function () {
            $('#imageInput').on('change', function () {
                var file = this.files[0];
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#posterImg').removeClass('d-none');
                    $('#posterImage').attr('src', e.target.result);
                }

                reader.readAsDataURL(file);
            });
        });
    </script>
}

MovieApp.UI/Views/Movie/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using MovieApp.Core.Domain.IdentityEntites
@using MovieApp.Core.ServicesContracts
@model IEnumerable<MovieResponse>
@inject IMovieFavouriteServices _movieFavouriteService
@inject UserManager<ApplicationUser> _userManager;
@{
    ViewData["Title"] = "Index";
    string searchString = ViewBag.currentSearchString as string;
    string currentSortBy = ViewBag.currentSortBy as string;
    string currentSorted = ViewBag.currentSorted as string;
    var user = await _userManager.GetUserAsync(User);
}

<h2>
    <i class="bi bi-film"></i>
    Movies
</h2>
<hr />
<form asp-action="Index" asp-controller="Movie" method="get">
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="input-group mb-3">
                    <input name="searchString" value="@searchString" type="text" class="form-control" placeholder="Search for movies..." aria-label="Search for movies" aria-describedby="button-search">
                    <button class="btn btn-primary" type="submit" id="button-search">
                        <i class="bi bi-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="d-flex justify-content-between align-items-center mb-3">
        @if(User.IsInRole("ADMIN"))
        {
            <a asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle-fill"></i>
                Add Movie
            </a>
        }
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="input-group mb-3">
                    <select name="sortBy" class="form-select" aria-label="Order by" id="order-by-select">
                        @foreach (var select in ViewBag.sortByList)
                        {
                            if (select.Value == currentSortBy)
                            {
                                <option value="@select.Value" selected>@select.Text</option>
                            }
                            else
                            {
                                <option value="@select.Value">@select.Text</option>
                            }
                        }
                    </select>
                    <input type="hidden" name="sorted" value="@(currentSorted == "ASC" ? "DESC" : "ASC")" />
                    <button class="btn btn-primary" type="submit" id="order-by-button">
                        <i class="bi bi-arrow-down-up"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3">
        @if (!Model.Any())
        {
            <div class="alert alert-warning" role="alert">
                No Movie Found
            </div>
        }
        else
        {
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
                @foreach (var movie in Model)
                {
                    <div class="col">
                        <div class="card h-100">
                            <img src="/Upload/@movie.ImageURL" class="card-img-top movie-image" alt="Movie Poster">
                            <div class="card-body">
                                <h5 class="card-title">@movie.Title</h5>
                                <p class="card-text">@movie.Description.Substring(0, Math.Min(movie.Description.Length, 100))...</p>
                            </div>
                            <div class="card-footer bg-transparent border-top-0">
                                <div class="d-flex flex-column">
                                    <div class="d-flex justify-content-between align-items-center mb-2">
                                        <div class="d-flex align-items-center">
                                            <i class="bi bi-star-fill text-warning me-1"></i>
                                            <small class="text-muted">@movie.Rating?.ToString("0.0")</small>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-wrap justify-content-between btn-group" role="group" aria-label="Movie Actions">
                                        <a asp-action="Details" asp-route-MovieID="@movie.MovieID" class="btn btn-primary btn-sm flex-fill me-1 mb-1">
                                            <i class="bi bi-info-circle-fill"></i>
                                            Details
                                        </a>
                                        @if(User.IsInRole(nameof(UserOption.ADMIN)))
                                        {
                                            <a asp-action="Edit" asp-route-MovieID="@movie.MovieID" class="btn btn-warning btn-sm flex-fill me-1 mb-1">
                                                <i class="bi bi-pencil-fill"></i>
                                                Edit
                                            </a>
                                            <a asp-action="Delete" asp-route-MovieID="@movie.MovieID" class="btn btn-danger btn-sm flex-fill me-1 mb-1" onclick="return confirm('Are You Sure')">
                                                <i class="bi bi-trash-fill"></i>
                                                Delete
                                            </a>
                                        }
                                        @if(User.Identity.IsAuthenticated)
                                        {
                                            @if (!await _movieFavouriteService.IsMovieInUserFavourites(movie.MovieID, user.Id))
                                            {
                                                <form asp-action="AddMovieToUser" asp-controller="MovieFavourite" method="get" class="d-inline">
                                                    <input type="hidden" name="movieID" value="@movie.MovieID" />
                                                    <button type="submit" class="btn btn-outline-danger btn-sm flex-fill mb-1">
                                                        <i class="bi bi-heart"></i>
                                                    </button>
                                                </form>
                                            }
                                            else
                                            {
                                                <form asp-action="RemoveMovieFromUser" asp-controller="MovieFavourite" method="get" class="d-inline">
                                                    <input type="hidden" name="movieID" value="@movie.MovieID" />
                                                    <button type="submit" class="btn btn-outline-danger btn-sm flex-fill mb-1">
                                                        <img src="./Images/heart.png" width="25px" height="25px" />
                                                    </button>
                                                </form>
                                            }
                                        }
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</form>

<style>
    /* Custom styles for the search bar */
    .input-group .form-control {
        border-right: 0;
        box-shadow: none;
    }

    .input-group .btn {
        border-left: 0;
    }

    .input-group .form-control:focus {
        box-shadow: none;
        border-color: #007bff;
    }

    .input-group .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .input-group .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .movie-image {
        height: 350px;
        background-size: cover;
    }

    #order-by-select {
        flex: 1 1 auto;
    }

    #order-by-button {
        width: auto;
    }
</style>